const $ = selector => document.querySelector(selector);
let scores = { home: 1, away: 0 }, running = true, elapsed = 1458, period = 0;
const periods = ['1-й тайм', '2-й тайм', 'Доп. тайм', 'Пенальти'];
const dialog = $('#dialog');
function toast(text) { $('#toast').textContent = text; $('#toast').classList.add('show'); clearTimeout(toast.timeout); toast.timeout = setTimeout(() => $('#toast').classList.remove('show'), 2400); }
function modal(title, html) { $('#dialog-title').textContent = title; $('#dialog-content').innerHTML = html; dialog.showModal(); }
function render() { $('#home-score').textContent = scores.home; $('#away-score').textContent = scores.away; $('#clock').textContent = `${Math.floor(elapsed / 60).toString().padStart(2,'0')}:${(elapsed % 60).toString().padStart(2,'0')}`; $('#pause').textContent = running ? 'Ⅱ Пауза' : '▷ Продолжить'; }
$('#theme').addEventListener('click', () => document.body.classList.toggle('dark'));
$('#close-dialog').addEventListener('click', () => dialog.close());
dialog.addEventListener('click', event => { if (event.target === dialog) { const r = dialog.getBoundingClientRect(); if (event.clientX < r.left || event.clientX > r.right || event.clientY < r.top || event.clientY > r.bottom) dialog.close(); } });
document.querySelectorAll('[data-tab]').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('[data-tab]').forEach(b => b.classList.toggle('active', b === button)); document.querySelectorAll('[data-page]').forEach(page => page.hidden = page.dataset.page !== button.dataset.tab); window.scrollTo(0,0); }));
document.querySelectorAll('[data-goal]').forEach(button => button.addEventListener('click', () => { scores[button.dataset.goal]++; render(); $('#last-event').textContent = `${Math.floor(elapsed/60)}′ · Гол ${button.dataset.goal === 'home' ? 'Легиона' : 'соперника'}`; $('.event>span:last-child').textContent = `${scores.home} : ${scores.away}`; toast('Гол добавлен в демо'); }));
$('#pause').addEventListener('click', () => { running = !running; render(); });
$('#break').addEventListener('click', () => { running = false; $('#period-label').textContent = $('#score-period').textContent = 'Перерыв'; render(); });
$('#next').addEventListener('click', () => { modal('Период матча', '<p>Любой порядок игры. Время сохраняется; запуск — кнопкой «Продолжить».</p><select id="choose-period"><option>1-й тайм</option><option>2-й тайм</option><option>Доп. тайм</option><option>Пенальти</option></select><button class="primary full" id="apply-period">Выбрать</button>'); $('#apply-period').onclick = () => { $('#period-label').textContent = $('#score-period').textContent = $('#choose-period').value; dialog.close(); render(); }; });
$('#edit-score').addEventListener('click', () => { modal('Исправить счёт', `<label>Легион<input id="edit-home" type="number" min="0" value="${scores.home}"></label><label>Соперник<input id="edit-away" type="number" min="0" value="${scores.away}"></label><button class="primary full" id="save-score">Сохранить</button>`); $('#save-score').onclick = () => { scores.home = Math.max(0,parseInt($('#edit-home').value)||0); scores.away = Math.max(0,parseInt($('#edit-away').value)||0); render(); dialog.close(); }; });
$('#settings').addEventListener('click', () => { modal('Настройки матча', '<p>Источник данных</p><select id="mode"><option value="manual">Ручное управление</option><option value="full">Kimberly — всё автоматически</option><option value="score">Kimberly — только счёт</option></select><p>Легион · Некрасовка · 2016<br>Team ID: 17509</p><button class="primary full" id="save-mode">Применить к макету</button>'); $('#save-mode').onclick = () => { const manual = $('#mode').value === 'manual'; $('#source-label').textContent = manual ? 'Вручную' : 'Kimberly · демо'; $('#score-note').textContent = manual ? 'Счёт под вашим контролем' : 'Счёт из Kimberly · пример'; document.querySelectorAll('[data-goal]').forEach(b => b.disabled = !manual); $('#edit-score').hidden = !manual; dialog.close(); }; });
document.querySelectorAll('[data-intro]').forEach(button => button.addEventListener('click', () => modal(button.dataset.intro, `<div class="intro-sample"><img src="./data/legion-logo.svg" alt="Легион"><span> VS </span><img src="./data/default-opponent.svg" alt="Соперник"><h3>${button.dataset.intro}</h3></div><p>Локальный пример. Закройте крестиком или клавишей Escape.</p>`)));
$('#preview-goal').onclick = () => modal('Карточка гола', '<div class="goal-sample"><img src="./data/player-placeholder.svg" alt="Демонстрационный портрет"><div><small>ГОЛ · 18′</small><strong>ИВАНОВ</strong><small>№10 · Нападающий</small></div></div><p>Композиционный пример с заглушкой портрета. В рабочей версии — фото выбранного игрока.</p>');
$('#import').onclick = () => toast('В макете показан тестовый состав. Импорт подключим после согласования.');
document.querySelectorAll('[data-pos]').forEach(b => b.onclick = () => { $('#mini-bar').style.marginLeft = b.dataset.pos === 'left' ? '0' : 'auto'; document.querySelectorAll('[data-pos]').forEach(x => x.classList.toggle('selected',x===b)); });
document.querySelectorAll('[data-variant]').forEach(b => b.onclick = () => { $('#mini-bar').style.transform = b.dataset.variant === 'tv' ? 'skewX(-7deg)' : 'none'; $('#mini-bar').style.borderBottom = b.dataset.variant === 'layers' ? '5px solid #d2af54' : 'none'; document.querySelectorAll('[data-variant]').forEach(x => x.classList.toggle('selected',x===b)); });
document.querySelectorAll('[data-color]').forEach(b => b.onclick = () => $('#mini-bar').style.background = b.dataset.color);
$('#color').oninput = event => $('#mini-bar').style.background = event.target.value;
setInterval(() => { if(running) { elapsed++; render(); } },1000);
render();
